// <auto-generated />
namespace ForumApp_TestTask.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AppEmailConf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppEmailConf));
        
        string IMigrationMetadata.Id
        {
            get { return "202008211610229_AppEmailConf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
